before_install:
  - travis_retry gem install bundler
  - "rvm current | grep 'jruby' && export AR_JDBC=true || echo"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - rbx-2
  - jruby
env:
  - "GEM=railties"
  - "GEM=ap,am,amo,as,av"
  - "GEM=ar:mysql"
  - "GEM=ar:mysql2"
  - "GEM=ar:sqlite3"
  - "GEM=ar:postgresql"
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
  fast_finish: true