# .travis.yml
language: ruby
rvm:
  - 1.9.3
#before_install: 
#  - bundle exec gem update
#  - bundle exec update thread_safe
bundler_args: --without production
script:
  - RAILS_ENV=test 
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec  
#Deploy en Heroku
#Esto es un mix de lo que genero Travis, con otras opciones.
deploy:
  provider: heroku
#  buildpack: ruby
  api_key:
    secure: M+tLL8qNPShe6y80hXAf9dDE5YQXpWWdpXZZiWAUktppL0QFyqZM7jpyf8zzVTDRKRhTO8g7ToYvszgsUF1L1qJef1UicVuyEuKXXGhOU2peD2zYh2eo+ns/k0Yo8PiP3zrkWIt9qK72dnRFQ9YUwSuSoGmErRyHLnmyovdcI0k=
  app: tfa-vox
  on:
    repo: matiasmasca/vox
  run:
    - "rake db:drop"
    - "rake db:schema:load --trace"
    - restart

#db:schema:load #creates tables and columns within the (existing) database following schema.rb
#db:setup #does db:create, db:schema:load, db:seed

#after_script:
#  # Install the Heroku gem (or the Heroku toolbelt)
#  - gem install heroku
#  # Add your Heroku git repo:
#  - git remote add heroku git@heroku.com:YOUR_HEROKU_APP.git
#  # Add your Heroku API key:
#  - export HEROKU_API_KEY=YOUR_HEROKU_API_KEY_HERE
#  # Turn off warnings about SSH keys:
#  - echo "Host heroku.com" >> ~/.ssh/config
#  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
#  - echo "   CheckHostIP no" >> ~/.ssh/config
#  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
#  # Clear your current Heroku SSH keys:
#  - heroku keys:clear
#  # Add a new SSH key to Heroku
#  - yes | heroku keys:add
#  # Push to Heroku!
#  - yes | git push heroku master