# .travis.yml
language: ruby
rvm:
  - 1.9.3
#before_install: 
#  - bundle exec gem update
#  - bundle exec update thread_safe
bundler_args: --without production
script:
  - RAILS_ENV=test 
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - xvfb-run bundle exec rspec spec/*.rb 
