# .travis.yml
language: ruby
rvm:
  - 1.9.3
bundler_args: --without production
script:
#  - RAILS_ENV=test 
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
#  - xvfb-run bundle exec rspec spec/*.rb 
