require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SelectionProcessController do

  # This should return the minimal set of attributes required to create a valid
  # SelectionProcesses. As you add validations to SelectionProcesses, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name_process" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SelectionProcessController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all selection_processes as @selection_processes" do
      selection_processes = SelectionProcesses.create! valid_attributes
      get :index, {}, valid_session
      assigns(:selection_process).should eq([selection_processes])
    end
  end

  describe "GET show" do
    it "assigns the requested selection_processes as @selection_processes" do
      selection_processes = SelectionProcesses.create! valid_attributes
      get :show, {:id => selection_processes.to_param}, valid_session
      assigns(:selection_processes).should eq(selection_processes)
    end
  end

  describe "GET new" do
    it "assigns a new selection_processes as @selection_processes" do
      get :new, {}, valid_session
      assigns(:selection_processes).should be_a_new(SelectionProcesses)
    end
  end

  describe "GET edit" do
    it "assigns the requested selection_processes as @selection_processes" do
      selection_processes = SelectionProcesses.create! valid_attributes
      get :edit, {:id => selection_processes.to_param}, valid_session
      assigns(:selection_processes).should eq(selection_processes)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SelectionProcesses" do
        expect {
          post :create, {:selection_processes => valid_attributes}, valid_session
        }.to change(SelectionProcesses, :count).by(1)
      end

      it "assigns a newly created selection_processes as @selection_processes" do
        post :create, {:selection_processes => valid_attributes}, valid_session
        assigns(:selection_processes).should be_a(SelectionProcesses)
        assigns(:selection_processes).should be_persisted
      end

      it "redirects to the created selection_processes" do
        post :create, {:selection_processes => valid_attributes}, valid_session
        response.should redirect_to(SelectionProcesses.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved selection_processes as @selection_processes" do
        # Trigger the behavior that occurs when invalid params are submitted
        SelectionProcesses.any_instance.stub(:save).and_return(false)
        post :create, {:selection_processes => { "name_process" => "invalid value" }}, valid_session
        assigns(:selection_processes).should be_a_new(SelectionProcesses)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SelectionProcesses.any_instance.stub(:save).and_return(false)
        post :create, {:selection_processes => { "name_process" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested selection_processes" do
        selection_processes = SelectionProcesses.create! valid_attributes
        # Assuming there are no other selection_process in the database, this
        # specifies that the SelectionProcesses created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SelectionProcesses.any_instance.should_receive(:update).with({ "name_process" => "MyString" })
        put :update, {:id => selection_processes.to_param, :selection_processes => { "name_process" => "MyString" }}, valid_session
      end

      it "assigns the requested selection_processes as @selection_processes" do
        selection_processes = SelectionProcesses.create! valid_attributes
        put :update, {:id => selection_processes.to_param, :selection_processes => valid_attributes}, valid_session
        assigns(:selection_processes).should eq(selection_processes)
      end

      it "redirects to the selection_processes" do
        selection_processes = SelectionProcesses.create! valid_attributes
        put :update, {:id => selection_processes.to_param, :selection_processes => valid_attributes}, valid_session
        response.should redirect_to(selection_processes)
      end
    end

    describe "with invalid params" do
      it "assigns the selection_processes as @selection_processes" do
        selection_processes = SelectionProcesses.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SelectionProcesses.any_instance.stub(:save).and_return(false)
        put :update, {:id => selection_processes.to_param, :selection_processes => { "name_process" => "invalid value" }}, valid_session
        assigns(:selection_processes).should eq(selection_processes)
      end

      it "re-renders the 'edit' template" do
        selection_processes = SelectionProcesses.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SelectionProcesses.any_instance.stub(:save).and_return(false)
        put :update, {:id => selection_processes.to_param, :selection_processes => { "name_process" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested selection_processes" do
      selection_processes = SelectionProcesses.create! valid_attributes
      expect {
        delete :destroy, {:id => selection_processes.to_param}, valid_session
      }.to change(SelectionProcesses, :count).by(-1)
    end

    it "redirects to the selection_process list" do
      selection_processes = SelectionProcesses.create! valid_attributes
      delete :destroy, {:id => selection_processes.to_param}, valid_session
      response.should redirect_to(selection_process_url)
    end
  end

end
